- name: Count Lines of Code (cloc)
  uses: djdefi/cloc-action@6
            
language: scala
scala:
- 2.12.7

script:
- sbt clean coverage test coverageReport

after_success:
- sbt coverageReport coveralls