name: Count Lines of Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Count Lines of Code (cloc)
        uses: djdefi/cloc-action@6

name: Scala CI

on:
  push:
    branches: [ "master", "CDP" ]
  pull_request:
    branches: [ "master", "CDP" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: 'sbt'
      - name: compile
        run: sbt compile
      - name: run tests
        run: sbt test

  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'corretto'
          cache: 'sbt'
      - name: Run Tests
        run: sbt clean coverage test
      - name: Upload Coverage Report
        env:
            COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sbt coverageReport coveralls
